sudo: required

before_install:
    - docker pull mrokkk/devel

matrix:
    include:
        - env:
            - IMAGE=mrokkk/devel
            - JOB=coverage
            - COMPILER=g++
            - CODECOV=1
          install:
            - sudo apt-get install python-pip
            - sudo pip install codecov
          services:
            - docker

        - env:
            - IMAGE=mrokkk/devel
            - JOB=valgrind
            - COMPILER=g++
          services:
            - docker

        - env:
            - IMAGE=mrokkk/devel
            - JOB=coverage
            - COMPILER=clang++
            - CPP_STANDARD=c++11
          services:
            - docker

        - env:
            - IMAGE=mrokkk/devel
            - JOB=coverage
            - COMPILER=clang++
            - CPP_STANDARD=c++14
          services:
            - docker

        - env:
            - IMAGE=mrokkk/devel
            - JOB=coverage
            - COMPILER=clang++
            - CPP_STANDARD=c++1z
          services:
            - docker

language: cpp

script: ./ci/ci.sh

after_success:
    - codecov

