sudo: required

before_install:
    - docker pull mrokkk/devel

install:
    - sudo apt-get install python-pip
    - sudo pip install codecov

matrix:
    include:
        - env:
            - IMAGE=mrokkk/devel
            - JOB=coverage
            - COMPILER=g++
            - CODECOV=1
          services:
            - docker

        - env:
            - IMAGE=mrokkk/devel
            - JOB=coverage
            - COMPILER=clang++
          services:
            - docker

        - env:
            - IMAGE=mrokkk/devel
            - JOB=valgrind
            - COMPILER=g++
          services:
            - docker

language: cpp

script: ./ci/ci.sh

after_success:
    - codecov

